app/cf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.TicketListView.as_view(), name="list"),
    path("add/", views.TicketCreateView.as_view(), name="create"),
    path("ticket/<slug:slug>/", views.TicketDetailView.as_view(), name="detail"),
]

app/core/models.py
from email.policy import default
import uuid

from django.conf import settings
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

User = settings.AUTH_USER_MODEL


class TicketStatus(models.Model):
    ticket_status = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "tickets statuses"

    def __str__(self):
        return self.ticket_status.upper()


class Category(models.Model):
    category = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category


class Ticket(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    slug = models.SlugField(max_length=65, blank=True, null=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name="ticket_categories",
        null=True,
        blank=True,
    )
    ticket_status = models.ForeignKey(
        TicketStatus, on_delete=models.CASCADE, related_name="ticket_statuses", default=5
    )
    ticket_title = models.CharField(max_length=100)
    ticket_detail = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="ticket_created_by", null=True
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="ticket_updated_by", null=True
    )
    
    def get_absolute_url(self):
        return reverse('core:detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.uid)
        super(Ticket, self).save(*args, **kwargs)

    def __str__(self):
        return self.ticket_title


class TicketComment(models.Model):
    ticket = models.ForeignKey(
        Ticket, on_delete=models.CASCADE, related_name="comments", null=True, blank=True
    )
    comment = models.TextField()
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comment_created_by"
    )
    updated_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="comment_updated_by"
    )

    def __str__(self):
        return self.comment + " | " + self.ticket.ticket_title

app/users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify

# from django.urls import reverse


class User(AbstractUser):
    is_help_desk = models.BooleanField(default=False)
    is_tech = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=True)


class Agency(models.Model):
    agency_name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "agencies"

    def __str__(self):
        return self.agency_name


class UserProfile(models.Model):
    GENDER_LIST = [
        ("M", "M"),
        ("F", "F"),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    uid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    first_name = models.CharField(max_length=65, blank=True)
    last_name = models.CharField(max_length=65, blank=True)
    agency = models.ForeignKey(
        Agency, on_delete=models.CASCADE, related_name="agencies", null=True, blank=True
    )
    slug = models.SlugField(max_length=65, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_LIST)
    dob = models.DateField("DOB", blank=True, null=True)
    bio = models.TextField(blank=True)
    phone = models.CharField(max_length=25, blank=True, default="+ 1758")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.uid)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.user.username

app/core/views.py
from django.shortcuts import render
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .models import Ticket


class TicketListView(ListView):
    model = Ticket


class TicketCreateView(CreateView):
    model = Ticket
    fields = "__all__"


class TicketDetailView(DetailView):
    model = Ticket

app/users/views.py
from django.shortcuts import render

# Create your views here.

app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
    <link rel="stylesheet"
        href="{% static 'css/custom.css' %}">

    <title>

        {% block head_title %}

        {% endblock head_title %}
        Tickets
    </title>
</head>

<body>

    {% include 'header.html' %}

    {% block content %}

    {% endblock content %}

    {% include 'footer.html' %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
</body>

</html>

app/templates/core/ticket_detail.html
{% extends 'base.html' %}


{% block head_title %}
{{object.pk}}
{% endblock head_title %}



{% block content %}
<div class="vh-100">
    <div class="my-5 container">
        <a href="/">back</a>
    </div>
    <div class="col-lg-4 mx-auto">
        <h2 class="text-end">#{{object.pk}}</h2>
        <div class="card">
            <div class="card-header">{{object.ticket_status}}</div>
            <div class="card-body">
                <p>{{object.category|upper}}</p>
                <p>{{object.ticket_title}}</p>
                <p>{{object.ticket_detail}}</p>
                <p>{{object.created_by}}</p>
            </div>
        </div>
        <div class="container small">
            <br>
            {% for comment in object.comments.all %}
            {{comment}}
            <p class="small text-muted text-end">{{comment.created_by}}</p>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

app/templates/core/ticket_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block blockname %}

{% endblock blockname %}


{% block content %}
<div class="container my-5">
    <div class="col-lg-4 mx-auto">
        <h2 class="text-center">Form</h2>
        <div class="border shadow" style="border-radius: 1rem;">
            <div class="card-body mt-3">
                <form action=""
                    method="post">
                    {% csrf_token %}
                    {{form|crispy}}
                    <div class="text-end">
                        <button class="btn btn-sm btn-outline-dark px-5 mt-3"
                            type="submit">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/core/ticket_list.html
{% extends 'base.html' %}

{% block head_title %}
List
{% endblock head_title %}

{% block content %}
<div class="mx-5 vh-100">
    <div class="row">
        <div class="col">
            <div class="">
                <div class="row">
                    <div class="col">
                        <div class="h1">Ticket</div>
                    </div>
                    <div class="col">
                        <a class="text-decoration-none text-dark d-flex justify-content-end"
                            href="{% url 'core:create' %}">
                            <i title="add ticket"
                                class="bi bi-plus-circle-fill fs-3"></i>
                        </a>
                    </div>
                </div>
                <br>
                <div class="border p-5 shadow"
                    style="border-radius: 1rem ;">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">ticket</th>
                                <th scope="col">category</th>
                                <th scope="col">status</th>
                                <th scope="col">created by</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for ticket in object_list %}
                            <tr>
                                <th scope="row">{{ forloop.counter }} </th>
                                <td>
                                    <a class="text-decoration-none text-dark"
                                        href="{{ ticket.get_absolute_url }}">{{ticket.ticket_title}}</a>
                                </td>
                                <td>{{ticket.category}}</td>
                                <td>{{ticket.ticket_status}}</td>
                                <td>{{ticket.created_by}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-2">
            {% include 'core/zone_list.html' %}
        </div>
    </div>
</div>
{% endblock content %}

app/templates/core/zone_list.html
<div class="px-2 py-3">
    <br>
    <div class="h4 text-center">Zone Assignments</div>
    <div class="border pt-5 px-3 shadow"
        style="border-radius:1rem;">
        {% for ticket in object_list %}
        <div class="d-flex">
            <a class="text-decoration-none text-dark mx-auto"
                href="">Text</a>
            <a class="text-decoration-none text-dark mx-auto"
                href="">Text</a>
        </div>
        <hr>
        {% endfor %}
    </div>
</div>

app/templates/footer.html
<div class="container">
    <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/"
                class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi"
                    width="30"
                    height="24">
                    <use xlink:href="#bootstrap" />
                </svg>
            </a>
            <span class="text-muted">&copy; <a
                    class="text-decoration-none text-dark"
                    target="_blank"
                    href="https://ksslu.com/">kingship</a></span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-dark"
                    href="#"><i class="bi bi-twitter fs-4"></i></a></li>
            <li class="ms-3"><a class="text-dark"
                    href="#"><i class="bi bi-instagram fs-4"></i></a></li>
            <li class="ms-3"><a class="text-dark"
                    href="#"><i class="bi bi-facebook fs-4"></i></a></li>
        </ul>
    </footer>
</div>

app/templates/header.html
{% if request.user.is_authenticated %}


<header class="p-3 mb-3 border-bottom bg-dark">
    <div class="container">
        <div
            class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul
                class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'core:list' %}"
                        class="nav-link px-2 link-light">Tickets</a></li>
                <li><a href="{% url 'core:create' %}"
                        class="nav-link px-2 link-light">Create ticket</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search"
                    class="form-control"
                    placeholder="Search..."
                    aria-label="Search">
            </form>

            <div class="dropdown text-end">
                <a href="#"
                    class="d-block link-light text-decoration-none dropdown-toggle"
                    id="dropdownUser1"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">
                    <i class="bi bi-file-person fs-3"></i>
                    <!-- <img src="https://github.com/mdo.png"
                        alt="mdo"
                        width="32"
                        height="32"
                        class="rounded-circle"> -->
                </a>
                <ul class="dropdown-menu text-small"
                    aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item"
                            href="#">Profile</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item"
                            href="{% url 'account_logout' %}">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

{% else %}
<header class="p-3 mb-3 border-bottom bg-dark">
    <div class="container">
        <div
            class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul
                class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#"
                        class="nav-link px-2 link-light">Create ticket</a></li>
                <li><a href="{% url 'account_login' %}"
                        class="nav-link px-2 link-light">Login</a></li>
            </ul>
        </div>
    </div>
</header>
{% endif %}